package com.cust.mdm.cust.path;

import com.orchestranetworks.schema.*;
/**
 * Generated by EBX5 5.8.1 fix C [1067:0007], at  2018/03/21 14:49:03 [EDT].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: cust-mdm, path: /WEB-INF/ebx/schemas/CustReferenceDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/'   relativeToRoot: false
 * 
 */
public interface CustReferencePaths
{
	// ===============================================
	// Constants for nodes under '/'.
	// Prefix:  ''.
	// Statistics:
	//		1 path constants.
	//		0 leaf nodes.
	public static final Path _Root = Path.parse("/root");
	// ===============================================

}
