package com.cust.mdm.cust.path;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1166:r95059, at 2021/11/09 16:55:18 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: cust-mdm, path: /WEB-INF/ebx/schemas/DataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface CustPaths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		93 path constants.
	//		31 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Store
	{
		private static final Path _Root_Store = _Root.add("Store");
		public static Path getPathInSchema()
		{
			return _Root_Store;
		}
		public static final Path _Root_Store_Identifier = Path.parse("./identifier");
		public static final Path _Root_Store_Inventories = Path.parse("./inventories");
		public static final Path _Root_Store_Name = Path.parse("./name");
		public static final Path _Root_Store_Type = Path.parse("./type");
		public static final Path _Root_Store_Address = Path.parse("./address");
		public static final Path _Root_Store_Address_Street = Path.parse("./address/street");
		public static final Path _Root_Store_Address_City = Path.parse("./address/city");
		public static final Path _Root_Store_Address_Region = Path.parse("./address/region");
		public static final Path _Root_Store_Address_Postcode = Path.parse("./address/postcode");
		public static final Path _Root_Store_Address_Country = Path.parse("./address/country");
	} 

	// Table type path
	public final class _Root_Category
	{
		private static final Path _Root_Category = _Root.add("Category");
		public static Path getPathInSchema()
		{
			return _Root_Category;
		}
		public static final Path _Root_Category_Identifier = Path.parse("./identifier");
		public static final Path _Root_Category_Parent = Path.parse("./parent");
		public static final Path _Root_Category_Name = Path.parse("./name");
		public static final Path _Root_Category_Comment = Path.parse("./comment");
	} 

	// Table type path
	public final class _Root_Brand
	{
		private static final Path _Root_Brand = _Root.add("Brand");
		public static Path getPathInSchema()
		{
			return _Root_Brand;
		}
		public static final Path _Root_Brand_Identifier = Path.parse("./identifier");
		public static final Path _Root_Brand_Name = Path.parse("./name");
	} 

	// Table type path
	public final class _Root_Item
	{
		private static final Path _Root_Item = _Root.add("Item");
		public static Path getPathInSchema()
		{
			return _Root_Item;
		}
		public static final Path _Root_Item_Identifier = Path.parse("./identifier");
		public static final Path _Root_Item_Category = Path.parse("./category");
		public static final Path _Root_Item_Brand = Path.parse("./brand");
		public static final Path _Root_Item_Inventories = Path.parse("./inventories");
		public static final Path _Root_Item_Name = Path.parse("./name");
		public static final Path _Root_Item_Available = Path.parse("./available");
		public static final Path _Root_Item_DefaultPrice = Path.parse("./defaultPrice");
	} 

	// Table type path
	public final class _Root_Inventory
	{
		private static final Path _Root_Inventory = _Root.add("Inventory");
		public static Path getPathInSchema()
		{
			return _Root_Inventory;
		}
		public static final Path _Root_Inventory_Item = Path.parse("./item");
		public static final Path _Root_Inventory_Store = Path.parse("./store");
		public static final Path _Root_Inventory_Stock = Path.parse("./stock");
		public static final Path _Root_Inventory_Price = Path.parse("./price");
		public static final Path _Root_Inventory_Modified = Path.parse("./modified");
		public static final Path _Root_Inventory_Total = Path.parse("./Total");
	} 

	// Table type path
	public final class _Root_AgeTable
	{
		private static final Path _Root_AgeTable = _Root.add("AgeTable");
		public static Path getPathInSchema()
		{
			return _Root_AgeTable;
		}
		public static final Path _Root_AgeTable_Age = Path.parse("./Age");
		public static final Path _Root_AgeTable_Date = Path.parse("./Date");
		public static final Path _Root_AgeTable_Sr = Path.parse("./sr");
	} 
	// ===============================================

}
