package com.cust.mdm;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1166:r95059, at 2021/11/09 16:55:18 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: cust-mdm, path: /WEB-INF/ebx/schemas/Demo.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface MyPath
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		25 path constants.
	//		4 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Prac
	{
		private static final Path _Root_Prac = _Root.add("prac");
		public static Path getPathInSchema()
		{
			return _Root_Prac;
		}
		public static final Path _Root_Prac_Id = Path.parse("./id");
		public static final Path _Root_Prac_Name = Path.parse("./name");
	} 

	// Table type path
	public final class _Root_Prac2
	{
		private static final Path _Root_Prac2 = _Root.add("prac2");
		public static Path getPathInSchema()
		{
			return _Root_Prac2;
		}
		public static final Path _Root_Prac2_C1 = Path.parse("./c1");
		public static final Path _Root_Prac2_C2 = Path.parse("./c2");
	} 
	// ===============================================

}
