package com.cust.mdm.CustAssign;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1166:r95059, at 2021/11/09 16:55:18 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: cust-mdm, path: /WEB-INF/ebx/schemas/DataAssignment.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Mypaths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		51 path constants.
	//		17 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Customer
	{
		private static final Path _Root_Customer = _Root.add("Customer");
		public static Path getPathInSchema()
		{
			return _Root_Customer;
		}
		public static final Path _Root_Customer_ID = Path.parse("./ID");
		public static final Path _Root_Customer_CustomerMain = Path.parse("./CustomerMain");
		public static final Path _Root_Customer_CustomerMain_Name = Path.parse("./CustomerMain/Name");
		public static final Path _Root_Customer_CustomerMain_Type = Path.parse("./CustomerMain/Type");
		public static final Path _Root_Customer_CustomerMain_UserID = Path.parse("./CustomerMain/UserID");
		public static final Path _Root_Customer_CustomerMain_CreatedDate = Path.parse("./CustomerMain/CreatedDate");
		public static final Path _Root_Customer_CustomerMain_Create_difference_in_Days = Path.parse("./CustomerMain/Create_difference_in_Days");
		public static final Path _Root_Customer_CustomerAddresses = Path.parse("./CustomerAddresses");
		public static final Path _Root_Customer_CustomerAddresses_CustomerAddress = Path.parse("./CustomerAddresses/CustomerAddress");
	} 

	// Table type path
	public final class _Root_Address
	{
		private static final Path _Root_Address = _Root.add("Address");
		public static Path getPathInSchema()
		{
			return _Root_Address;
		}
		public static final Path _Root_Address_ID = Path.parse("./ID");
		public static final Path _Root_Address_Address = Path.parse("./Address");
		public static final Path _Root_Address_Address_Address_Line_1 = Path.parse("./Address/Address_Line_1");
		public static final Path _Root_Address_Address_Address_Line_2 = Path.parse("./Address/Address_Line_2");
		public static final Path _Root_Address_Address_City = Path.parse("./Address/City");
		public static final Path _Root_Address_Address_Country = Path.parse("./Address/Country");
		public static final Path _Root_Address_Address_State = Path.parse("./Address/State");
		public static final Path _Root_Address_Address_ZipCode = Path.parse("./Address/ZipCode");
	} 

	// Table type path
	public final class _Root_CustomerAddress
	{
		private static final Path _Root_CustomerAddress = _Root.add("CustomerAddress");
		public static Path getPathInSchema()
		{
			return _Root_CustomerAddress;
		}
		public static final Path _Root_CustomerAddress_Type = Path.parse("./Type");
		public static final Path _Root_CustomerAddress_AddressID = Path.parse("./AddressID");
		public static final Path _Root_CustomerAddress_CustomerID = Path.parse("./CustomerID");
	} 
	// ===============================================

}
