package com.cust.mdm.CustAssign;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1166:r95059, at 2021/11/09 16:55:18 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: cust-mdm, path: /WEB-INF/ebx/schemas/CommonReference.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Mypaths1
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		26 path constants.
	//		5 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Countries
	{
		private static final Path _Root_Countries = _Root.add("Countries");
		public static Path getPathInSchema()
		{
			return _Root_Countries;
		}
		public static final Path _Root_Countries_Code = Path.parse("./Code");
		public static final Path _Root_Countries_Name = Path.parse("./Name");
	} 

	// Table type path
	public final class _Root_Subdivision
	{
		private static final Path _Root_Subdivision = _Root.add("Subdivision");
		public static Path getPathInSchema()
		{
			return _Root_Subdivision;
		}
		public static final Path _Root_Subdivision_Code = Path.parse("./Code");
		public static final Path _Root_Subdivision_Name = Path.parse("./Name");
		public static final Path _Root_Subdivision_Countries = Path.parse("./Countries");
	} 
	// ===============================================

}
