package com.cust.mdm2;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1166:r95059, at 2021/11/09 16:55:18 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: cust-mdm, path: /WEB-INF/ebx/schemas/Demo1.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root/prac'   relativeToRoot: false
 * 
 */
public interface MyPath1
{
	// ===============================================
	// Constants for nodes under '/root/prac'.
	// Statistics:
	//		3 path constants.
	//		2 leaf nodes.
	public static final Path _Root_Prac = Path.parse("/root/prac");
	public static final Path _Root_Prac_Id = _Root_Prac.add("id");
	public static final Path _Root_Prac_Name = _Root_Prac.add("name");
	// ===============================================

}
