package com.cust.mdm2;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1166:r95059, at 2021/11/09 16:55:18 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: cust-mdm, path: /WEB-INF/ebx/schemas/Demo1.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root/prac2'   relativeToRoot: false
 * 
 */
public interface MyPath2
{
	// ===============================================
	// Constants for nodes under '/root/prac2'.
	// Statistics:
	//		3 path constants.
	//		2 leaf nodes.
	public static final Path _Root_Prac2 = Path.parse("/root/prac2");
	public static final Path _Root_Prac2_C1 = _Root_Prac2.add("c1");
	public static final Path _Root_Prac2_C2 = _Root_Prac2.add("c2");
	// ===============================================

}
